import type { NextPage } from 'next'
import Head from 'next/head'
import {useEffect, useState} from 'react'
import Espacio from '../components/espacio'
import Nave from '../components/Nave'
import styles from '../styles/Home.module.css'



const Home: NextPage = () => {
  const [nave, setNave] = useState(false);
  useEffect(() => {
    const handleScroll = () => {
      console.log(window.scrollY);
    }
    window.addEventListener('scroll', handleScroll);
    if (window.scrollY > 100) {
      setNave(!nave);
    }
  }, []);
  return (
    <div className={styles.container}>
      
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button style={{position: 'absolute', top: '5px', left: '5px'}} onClick={() => {setNave(!nave);} }/>
        <Nave isVisible={nave}/>
        <Espacio isVisible={!nave}/>
      </main>
      </div>
  )
}

export default Home
