import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import Espacio from "../components/espacio";
import Nave from "../components/Nave";
import ProtectoIndividual from "../components/ProyectoIndividual";
import ProtectoGrupal from "../components/ProtectoGrupal";
import styles from "../styles/Home.module.css";
import bStyles from "../styles/buttons.module.css";

const Home: NextPage = () => {
  const [nave, setNave] = useState(1);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" rel="noopener noreferrer" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={bStyles.container}>
          <button
            className={nave === 1 ? bStyles.active : bStyles.inactive}
            onClick={() => {
              setNave(1);
            }}
          >
            Ir al inicio
          </button>
          <button
            className={nave === 2 ? bStyles.active : bStyles.inactive}
            onClick={() => {
              setNave(2);
            }}
          >
            Proyecto PI Food
          </button>
          <button
            className={nave === 3 ? bStyles.active : bStyles.inactive}
            onClick={() => {
              setNave(3);
            }}
          >
            Proyecto Salvatore Dietetica
          </button>
          <button
            className={nave === 4 ? bStyles.active : bStyles.inactive}
            onClick={() => {
              setNave(4);
            }}
          >
            Ver info de contacto
          </button>
        </div>
        <Espacio isVisible={nave === 1} />
        <ProtectoIndividual isVisible={nave === 2} />
        <ProtectoGrupal isVisible={nave === 3} />
        <Nave isVisible={nave === 4} />
      </main>
    </div>
  );
};

export default Home;
